// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  minutesSidebar: [
    {
      type: 'doc',
      id: 'minutes/index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Advisors Minutes',
      collapsed: false,
      items: [
        'minutes/advisors/minute-01',
      ],
    },
    {
      type: 'category',
      label: 'Team Minutes',
      collapsed: false,
      items: [
        'minutes/team/minute-02',
      ],
    },
  ],
};

module.exports = sidebars;